### ISSUE TITLE
Change to sort in descending order (highest count first)

### ISSUE THREAD

**Issue by nodecentral** [Hoppi164/list_file_extensions#1]
Hi,

I’ve just tried your script , outputting to a text file, and it works really well however what can  i change so it sorts the listing in descending order (so the highest count of file types is first) ?

**Comment by Hoppi164** [comment]
Hi there!
Thanks for reaching out; this is a great suggestion.

I've updated the script to accept a new optional flag 
if you run `lfe.sh -d` it will now output the list in descending order

```
     64 .svg
     54 .jpg
     19 .js
      8 .css
      7 .pdf
      5 .png
      4 .gz
      3 .xlsx
      2 .csv
      1 .sh
      1 .json
      1 .html
```

Please feel free to make any more suggestions in the future :smiley:

**Comment by nodecentral** [comment]
Hi, many thanks, rather than a script, what would the full command be if it was just done as a single line (like before?)

**Comment by nodecentral** [comment]
I think i got it.. it’s the `sort -nr` part
````
 find . -type f | tr '[:upper:]' '[:lower:]' | grep -E ".*\.[a-zA-Z0-9]*$" | sed -e 's/.*\(\.[a-zA-Z0-9]*\)$/\1/' | sort | uniq -c | sort -nr > /share/Public/find_file_extention_count_v4.txt
````

Is there anyway to apply comma separation to the count ?

````
 204608 .jpg
 196150 .js
 126242 .pyc
 117383 .py
  98535 .h
  95812 .png
  88408 .eml
  69918 .svg
  50670 .gz
  49893 .json
````

**Comment by nodecentral** [comment]
Also, rather than file types, have you created code for other searches? I’d interested to know if you could do something that counted the number of files within a range of file sizes ? For example..
````
10 50000mb+
32 40000 - 49999mb
56 30000 - 39999mb

**Comment by Hoppi164** [comment]
Hi there

Yes making the last sort call `sort -nr` will do the trick reversing the output



In regard to adding commas to separate the thousands figure id suggest modifying the `sed` part of the code to transform this in

Here's a relevant article that may help with this. 

https://shallowsky.com/blog/linux/cmdline/sed-insert-commas.html



In regards to making the script search for files with sizes within certain ranges:
I can see the benefit of something like this, however it's definitely outside the range of lfe which is entirely designed to print file extensions. 
I won't be modifying the script to achieve this goal as it will muddy the waters of the scripts original purpose. 


If you were to create something like this in a similar manner id suggest piping the output to a `ls -l` command into sed to extract the file size and transform the output into predefined groups.
